[workspace]
members = [
    "inputshare-client",
    "inputshare-server",
    "lib/inputshare-common",
    "lib/yawi",
]
exclude = [
    "inputshare-esp32"
]

[profile.release]
lto = true
split-debuginfo = "packed"
#strip="symbols"